services:
  - type: web
    name: sidhivinayaksoftwork-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations content && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /health/
databases:
  - name: sidhivinayaksoftwork-db
    databaseName: sidhivinayaksoftwork
