# Generated by Django 5.2.17 on 2026-08-23 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('service', models.CharField(blank=True, max_length=120)),
                ('budget', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=80)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='sidhivinayaksoftwork', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(default='sidhivinayaksoftwork@gmail.com', max_length=254)),
                ('phone', models.CharField(default='9755550213', max_length=40)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='technologies/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('quote', models.TextField()),
                ('person_name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('resume', models.FileField(upload_to='applications/resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('status', models.CharField(default='new', max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('client', models.CharField(blank=True, max_length=120)),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='projects/')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.industry')),
                ('technologies', models.ManyToManyField(blank=True, to='content.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('problem', models.TextField()),
                ('strategy', models.TextField(blank=True)),
                ('implementation', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('hero_image', models.ImageField(blank=True, upload_to='case-studies/')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('meta_description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, to='content.blogtag')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.teammember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
